import 'fake-indexeddb/auto'
import { readFileSync } from 'node:fs'
import { afterEach, beforeAll, expect, it, vi } from 'vitest'
import { mountYuanStar } from '../public/yuanstar-embed/yuanstar-embed.js'
const workbook=readFileSync('public/yuanstar-embed/reference/YuanStar_Phase0_6A_经验星曜与突破材料规则_更新.xlsx')
let root, handle, serial=0
const settle=()=>new Promise(resolve=>setTimeout(resolve,100))
const routeIds=()=>[...root.querySelectorAll('[data-growth-route-id]')].map(e=>e.dataset.growthRouteId)
const change=(selector,value,type='change')=>{const field=root.querySelector(selector);field.value=value;field.dispatchEvent(new Event(type,{bubbles:true}))}
function expectEditorFollows(id,current,target) {
  expect(root.querySelector('#plan-rows .is-selected')?.dataset.starId).toBe(id)
  expect(root.querySelector('#growth-current-level').value).toBe(String(current))
  expect(root.querySelector('#growth-target-level').value).toBe(String(target))
}
beforeAll(()=>{URL.createObjectURL ||= ()=> 'blob:plan-test'; URL.revokeObjectURL ||= ()=>{}; window.scrollTo=()=>{}})
afterEach(async()=>{vi.useRealTimers(); await handle?.dispose(); root?.remove(); handle=null; vi.unstubAllGlobals()})
async function setup(options={}) {
  vi.stubGlobal('fetch',vi.fn(async()=>({ok:true,arrayBuffer:async()=>{ const bytes=new Uint8Array(workbook.length);bytes.set(workbook);return bytes.buffer }})))
  root=document.createElement('div');root.id='product-root';document.body.appendChild(root)
  const account={accountId:'growth-probe-'+ ++serial,displayName:'P1 测试账号 '+serial,gameVersion:'如鸢'}
  handle=mountYuanStar(root,{embedded:true,assetBaseUrl:'/yuanstar-embed/',hostAccount:account,...options})
  await handle.setHostAccount(account)
  await settle()
  await handle.applyCloudBusinessSnapshot({generation:1,revision:1,inventory:[
    {starInstanceId:'a',kind:'主星',name:'天府',quality:'橙',level:40},
    {starInstanceId:'b',kind:'主星',name:'天府',quality:'紫',level:43},
    {starInstanceId:'c',kind:'辅星',name:'文昌',quality:'橙',level:60}],planTargets:{a:50,b:52},bag:{currentCount:3,capacity:250},experience:{orange:1,purple:77,white:14}})
  handle.setActiveTab('review');handle.setReviewView('plan');await settle()
  expect(root.textContent).not.toContain('规则加载失败')
}
it('isolates plan rows, short resources and inert route cards from bag review',async()=>{
  const read=vi.fn(async()=>({jiezhuping:5,jiezheping:10,jieyangping:20}))
  await setup({onReadBreakthroughInventory:read})
  expect(root.querySelectorAll('#plan-rows input[type=checkbox]')).toHaveLength(0)
  expect(root.querySelectorAll('.growth-route-card')).toHaveLength(2)
  expect(root.querySelectorAll('.growth-route-card input:disabled')).toHaveLength(2)
  expect(root.querySelector('.growth-selection button').disabled).toBe(true)
  expect(root.querySelector('[data-growth-bottle="jiezhuping"]').value).toBe('5')
  expect(root.querySelector('.growth-resources').textContent).not.toMatch(/橙星曜|紫星曜|白星曜/)
  expect(root.querySelector('.ocr-review')).toBeNull();expect(root.querySelector('.experience-section')).toBeNull()
  expect(read).toHaveBeenCalled()
  handle.setReviewView('bag')
  expect(root.querySelectorAll('#plan-rows input[type=checkbox]')).toHaveLength(3)
  expect(root.querySelectorAll('#current-rows input[type=checkbox]')).toHaveLength(3)
  expect(root.querySelector('.ocr-review')).not.toBeNull();expect(root.querySelector('.experience-section').textContent).toContain('橙星曜')
})
it('selects rows by click and keyboard; summary double-click cancels pending single-click',async()=>{
  await setup()
  root.querySelector('[data-star-id="b"]').click()
  expect(root.querySelector('.growth-editor h2').textContent).toContain('天府')
  expect(root.querySelector('#growth-current-level').value).toBe('43')
  root.querySelector('[data-star-id="a"]').dispatchEvent(new KeyboardEvent('keydown',{key:' ',bubbles:true}))
  expect(root.querySelector('#growth-current-level').value).toBe('40')
  root.querySelector('[data-star-id="b"]').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}))
  expect(root.querySelector('#growth-current-level').value).toBe('43')
  root.querySelector('#view-mode-toggle').click();vi.useFakeTimers()
  let row=root.querySelector('[data-summary-group-key="主星|天府"]')
  row.click();vi.advanceTimersByTime(220)
  expect(root.querySelector('.summary-row.is-selected')).not.toBeNull()
  row=root.querySelector('[data-summary-group-key="主星|天府"]');row.click();vi.advanceTimersByTime(100);row.click();row.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));vi.advanceTimersByTime(250)
  expect(root.querySelector('#view-mode-toggle').textContent).toBe('逐颗明细')
  expect(root.querySelectorAll('#plan-rows [data-star-id]')).toHaveLength(2)
  root.querySelector('#view-mode-toggle').click()
  expect(root.querySelector('#view-mode-toggle').textContent).toBe('名称汇总')
  expect(root.querySelector('.summary-row.is-selected')).not.toBeNull()
})
it('previews levels and bottles without writing; explicit save preserves inventory quantities',async()=>{
  await setup()
  root.querySelector('[data-star-id="a"]').click()
  const before=await handle.getCloudBusinessSnapshot()
  const level=root.querySelector('#growth-current-level'),target=root.querySelector('#growth-target-level')
  level.value='43';level.dispatchEvent(new Event('input',{bubbles:true}));target.value='52';target.dispatchEvent(new Event('input',{bubbles:true}))
  expect([...root.querySelectorAll('.growth-edit-materials .growth-material-item')].map(e=>e.textContent.trim())).toEqual(['解注瓶 ×0','解谪瓶 ×60','解殃瓶 ×60'])
  expect(await handle.getCloudBusinessSnapshot()).toEqual(before)
  root.querySelector('#growth-save').click();await settle()
  const after=await handle.getCloudBusinessSnapshot()
  expect(after.inventory.find(star=>star.starInstanceId==='a').level).toBe(43);expect(after.planTargets.a).toBe(52)
  expect(after.experience).toEqual(before.experience);expect(after.bag).toEqual(before.bag)
})
it('drops stale bottle reads after account changes',async()=>{
  let resolve
  const pending=new Promise(done=>resolve=done)
  await setup({onReadBreakthroughInventory:owner=>owner.startsWith('growth-new-') ? Promise.resolve({jiezhuping:1,jiezheping:2,jieyangping:3}) : pending})
  await handle.setHostAccount({accountId:'growth-new-'+ ++serial,displayName:'另一个账号',gameVersion:'如鸢'})
  resolve({jiezhuping:999,jiezheping:999,jieyangping:999});await settle()
  expect(root.querySelector('[data-growth-bottle="jiezhuping"]').value).toBe('1')
  expect([...root.querySelectorAll('[data-growth-bottle]')].map(e=>e.value)).not.toContain('999')
})
it('edits real experience quantities and saves only the requested bottle through the host',async()=>{
  const save=vi.fn(async(owner,id,count)=>({jiezhuping:5,jiezheping:count,jieyangping:20}))
  await setup({onReadBreakthroughInventory:async()=>({jiezhuping:5,jiezheping:10,jieyangping:20}),onSaveBreakthroughInventory:save})
  const purple=root.querySelector('[data-growth-experience="purple"]')
  purple.value='80';purple.dispatchEvent(new Event('input',{bubbles:true}))
  expect(root.querySelector('.growth-owned-total b').textContent).toBe('42.4k')
  purple.dispatchEvent(new Event('change',{bubbles:true}));await settle()
  expect((await handle.getCloudBusinessSnapshot()).experience.purple).toBe(80)
  const bottle=root.querySelector('[data-growth-bottle="jiezheping"]')
  bottle.value='24';bottle.dispatchEvent(new Event('change',{bubbles:true}));await settle()
  expect(save).toHaveBeenCalledWith(expect.stringMatching(/^growth-probe-/),'jiezheping',24)
  expect(root.querySelector('[data-growth-bottle="jiezheping"]').value).toBe('24')
  expect(root.querySelector('#clear-filter')).toBeNull()
  expect(root.querySelector('#apply-filter').textContent).toBe('应用筛选')
})
it('route indices remain read-only and ignore edits without changing business state',async()=>{
  await setup()
  const before=await handle.getCloudBusinessSnapshot(), position=root.querySelector('[data-growth-route-id="b"]')
  const beforeOrder=[...root.querySelectorAll('[data-growth-route-id]')].map(e=>e.dataset.growthRouteId)
  expect(position.readOnly).toBe(true)
  position.value=position.value==='1' ? '2' : '1';position.dispatchEvent(new Event('change',{bubbles:true}))
  expect([...root.querySelectorAll('[data-growth-route-id]')].map(e=>e.dataset.growthRouteId)).toEqual(beforeOrder)
  expect(await handle.getCloudBusinessSnapshot()).toEqual(before)
})

it('kind and search filters drop hidden selection and drafts without pending-only',async()=>{
  await setup()
  root.querySelector('[data-star-id="b"]').click()
  change('#growth-current-level','44','input');change('#growth-target-level','59','input')
  change('#kind-filter','辅星')
  expectEditorFollows('c',60,60)
  change('#growth-target-level','58','input')
  change('#kind-filter','全部');change('#name-filter','天府','input');root.querySelector('#apply-filter').click()
  expectEditorFollows('b',43,52)
  change('#name-filter','贪狼','input');root.querySelector('#apply-filter').click()
  expect(root.querySelector('#growth-current-level')).toBeNull()
  expect(root.querySelector('#plan-rows .is-selected')).toBeNull()
  expect(root.querySelector('.growth-editor').textContent).toContain('选择一颗星石')
})

it('external removal resets the replacement editor and empty refresh clears it',async()=>{
  await setup();root.querySelector('[data-star-id="b"]').click()
  change('#growth-current-level','44','input');change('#growth-target-level','59','input')
  const before=await handle.getCloudBusinessSnapshot()
  await handle.applyCloudBusinessSnapshot({...before,generation:1,revision:2,inventory:before.inventory.filter(s=>s.starInstanceId!=='b'),planTargets:{a:50}})
  expectEditorFollows('a',40,50)
  await handle.applyCloudBusinessSnapshot({...before,generation:1,revision:3,inventory:[],planTargets:{},bag:{currentCount:0,capacity:250}})
  expect(root.querySelector('#growth-current-level')).toBeNull()
  expect(routeIds()).toEqual([])
  expect(root.querySelector('.growth-route-empty').textContent).toContain('当前账号')
})

it('summary switches clear drafts and double-click loads a visible instance with real levels',async()=>{
  await setup();root.querySelector('[data-star-id="a"]').click()
  change('#growth-current-level','41','input');change('#growth-target-level','59','input')
  root.querySelector('#view-mode-toggle').click()
  expect(root.querySelector('#growth-current-level')).toBeNull()
  root.querySelector('[data-summary-group-key="主星|天府"]').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}))
  expectEditorFollows('b',43,52)
  change('#growth-target-level','58','input');root.querySelector('#view-mode-toggle').click()
  expect(root.querySelector('#growth-current-level')).toBeNull()
  root.querySelector('#view-mode-toggle').click()
  expect(root.querySelector('#growth-current-level')).toBeNull()
  root.querySelector('[data-star-id="a"]').click();expectEditorFollows('a',40,50)
})

it('pending-only falls back and clears the hidden completed instance draft',async()=>{
  await setup();root.querySelector('[data-star-id="c"]').click()
  change('#growth-current-level','59','input')
  const pending=root.querySelector('#pending-only');pending.checked=true;pending.dispatchEvent(new Event('change',{bubbles:true}))
  expectEditorFollows('b',43,52)
})

it('all-account route IDs and default order ignore left search, kind, view, sort and pending-only',async()=>{
  await setup()
  const before=await handle.getCloudBusinessSnapshot()
  await handle.applyCloudBusinessSnapshot({...before,generation:1,revision:2,inventory:[...before.inventory,
    {starInstanceId:'d',kind:'主星',name:'贪狼',quality:'蓝',level:10},
    {starInstanceId:'e',kind:'辅星',name:'解神',quality:'绿',level:20}],planTargets:{a:50,b:52,d:60,e:50}})
  const initial=routeIds();expect(initial).toHaveLength(4)
  change('#name-filter','贪狼','input');root.querySelector('#apply-filter').click()
  expect(root.querySelectorAll('#plan-rows [data-star-id]')).toHaveLength(1);expect(routeIds()).toEqual(initial)
  change('#kind-filter','辅星');expect(root.querySelectorAll('#plan-rows [data-star-id]')).toHaveLength(0);expect(routeIds()).toEqual(initial)
  change('#name-filter','','input');root.querySelector('#apply-filter').click();change('#kind-filter','全部')
  for (const sort of ['name','level','target','catalog']) {change('#sort-filter',sort);expect(routeIds()).toEqual(initial)}
  const pending=root.querySelector('#pending-only');pending.checked=true;pending.dispatchEvent(new Event('change',{bubbles:true}));expect(routeIds()).toEqual(initial)
  root.querySelector('#view-mode-toggle').click();expect(routeIds()).toEqual(initial)
  root.querySelector('[data-summary-group-key="主星|贪狼"]').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));expect(routeIds()).toEqual(initial)
})

it('bottle conflict keeps the submitted target and displays retry feedback',async()=>{
  const save=vi.fn().mockRejectedValueOnce(new Error('解谪瓶库存可能已发生变化，保存结果与目标不一致。')).mockResolvedValue({jiezhuping:5,jiezheping:24,jieyangping:20})
  await setup({onReadBreakthroughInventory:async()=>({jiezhuping:5,jiezheping:10,jieyangping:20}),onSaveBreakthroughInventory:save})
  change('[data-growth-bottle="jiezheping"]','24');await settle()
  expect(root.querySelector('.growth-error').textContent).toContain('不一致')
  expect(root.querySelector('[data-growth-bottle="jiezheping"]').value).toBe('24')
  expect(root.querySelector('[data-growth-bottle="jiezhuping"]').value).toBe('5')
  expect(root.querySelector('[data-growth-bottle="jieyangping"]').value).toBe('20')
  root.querySelector('#growth-retry-inventory').click();await settle()
  expect(save).toHaveBeenCalledTimes(2);expect(save.mock.calls[1].slice(1)).toEqual(['jiezheping',24])
  expect(root.querySelector('#growth-retry-inventory')).toBeNull()
})
